image: "registry.gitlab.eelo.io:5000/eelo/docker-android-apps-cicd:latest"

stages:
- build
- publish

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew build
  artifacts:
    paths:
    - app/build/outputs/apk

publish-prebuiltapks:
  stage: publish
  script:
  - |
      curl --request POST \
      --form "token=$CI_JOB_TOKEN" \
      --form ref=master \
      --form "variables[PROJECT_PATH]=$CI_PROJECT_PATH" \
      --form "variables[JOB]=$CI_JOB_ID" \
      --form "variables[FILE_PATH]=app/build/outputs/apk/release/app-release-unsigned.apk" \
      https://gitlab.eelo.io/api/v4/projects/81/trigger/pipeline
